export interface Element {
  id: string;
  name: string;
  icon: string;
  description?: string;
  isBasic?: boolean;
  tier?: number; // 0-5, with 5 being the final dishes
  unlocked: boolean;
}

export interface ElementsState {
  [id: string]: Element;
}

// Define all game elements with their properties
export const createInitialElements = (): ElementsState => ({
  // TIER 0: Basic elements (starting elements)
  air: {
    id: 'air',
    name: 'Air',
    icon: 'air',
    description: 'One of the four basic elements.',
    isBasic: true,
    tier: 0,
    unlocked: true
  },
  earth: {
    id: 'earth',
    name: 'Earth',
    icon: 'earth',
    description: 'One of the four basic elements.',
    isBasic: true,
    tier: 0,
    unlocked: true
  },
  fire: {
    id: 'fire',
    name: 'Fire',
    icon: 'fire',
    description: 'One of the four basic elements.',
    isBasic: true,
    tier: 0,
    unlocked: true
  },
  water: {
    id: 'water',
    name: 'Water',
    icon: 'water',
    description: 'One of the four basic elements.',
    isBasic: true,
    tier: 0,
    unlocked: true
  },
  
  // TIER 1: Primary combinations (20 elements)
  steam: {
    id: 'steam',
    name: 'Steam',
    icon: 'steam',
    description: 'Water that has been heated to its boiling point.',
    tier: 1,
    unlocked: false
  },
  mud: {
    id: 'mud',
    name: 'Mud',
    icon: 'mud',
    description: 'A mixture of earth and water.',
    tier: 1,
    unlocked: false
  },
  dust: {
    id: 'dust',
    name: 'Dust',
    icon: 'dust',
    description: 'Small particles of earth suspended in air.',
    tier: 1,
    unlocked: false
  },
  energy: {
    id: 'energy',
    name: 'Energy',
    icon: 'energy',
    description: 'The power generated by fire and air together.',
    tier: 1,
    unlocked: false
  },
  lava: {
    id: 'lava',
    name: 'Lava',
    icon: 'lava',
    description: 'Molten rock created when fire meets earth.',
    tier: 1,
    unlocked: false
  },
  smoke: {
    id: 'smoke',
    name: 'Smoke',
    icon: 'smoke',
    description: 'Visible suspension of carbon particles resulting from fire.',
    tier: 1,
    unlocked: false
  },
  pressure: {
    id: 'pressure',
    name: 'Pressure',
    icon: 'pressure',
    description: 'Force applied to a surface by air or water.',
    tier: 1,
    unlocked: false
  },
  cloud: {
    id: 'cloud',
    name: 'Cloud',
    icon: 'cloud',
    description: 'Visible mass of water droplets in the air.',
    tier: 1,
    unlocked: false
  },
  rain: {
    id: 'rain',
    name: 'Rain',
    icon: 'rain',
    description: 'Water falling from clouds in drops.',
    tier: 1,
    unlocked: false
  },
  stone: {
    id: 'stone',
    name: 'Stone',
    icon: 'stone',
    description: 'A hard piece of mineral matter.',
    tier: 1,
    unlocked: false
  },
  sand: {
    id: 'sand',
    name: 'Sand',
    icon: 'sand',
    description: 'Small loose grains of worn or disintegrated rock.',
    tier: 1,
    unlocked: false
  },
  ash: {
    id: 'ash',
    name: 'Ash',
    icon: 'ash',
    description: 'Powdery residue left after burning something.',
    tier: 1,
    unlocked: false
  },
  clay: {
    id: 'clay',
    name: 'Clay',
    icon: 'clay',
    description: 'Fine-grained earth that can be molded when wet.',
    tier: 1,
    unlocked: false
  },
  salt: {
    id: 'salt',
    name: 'Salt',
    icon: 'salt',
    description: 'A crystalline mineral used for seasoning.',
    tier: 1,
    unlocked: false
  },
  algae: {
    id: 'algae',
    name: 'Algae',
    icon: 'algae',
    description: 'Simple aquatic organisms that grow in water.',
    tier: 1,
    unlocked: false
  },
  seed: {
    id: 'seed',
    name: 'Seed',
    icon: 'seed',
    description: 'A flowering plant\'s unit of reproduction.',
    tier: 1,
    unlocked: false
  },
  oil: {
    id: 'oil',
    name: 'Oil',
    icon: 'oil',
    description: 'A viscous liquid derived from plants or petroleum.',
    tier: 1,
    unlocked: false
  },
  light: {
    id: 'light',
    name: 'Light',
    icon: 'light',
    description: 'Electromagnetic radiation that enables sight.',
    tier: 1,
    unlocked: false
  },
  ice: {
    id: 'ice',
    name: 'Ice',
    icon: 'ice',
    description: 'Frozen water, solid state of H2O.',
    tier: 1,
    unlocked: false
  },
  time: {
    id: 'time',
    name: 'Time',
    icon: 'time',
    description: 'The indefinite continued progress of existence.',
    tier: 1,
    unlocked: false
  },
  heat: {
    id: 'heat',
    name: 'Heat',
    icon: 'heat',
    description: 'Energy that causes substances to rise in temperature.',
    tier: 1,
    unlocked: false
  },
  
  // TIER 2: Secondary combinations (30 elements)
  metal: {
    id: 'metal',
    name: 'Metal',
    icon: 'metal',
    description: 'A material that conducts heat and electricity.',
    tier: 2,
    unlocked: false
  },
  glass: {
    id: 'glass',
    name: 'Glass',
    icon: 'glass',
    description: 'A transparent substance made from melted sand.',
    tier: 2,
    unlocked: false
  },
  pottery: {
    id: 'pottery',
    name: 'Pottery',
    icon: 'pottery',
    description: 'Clay that has been shaped and fired.',
    tier: 2,
    unlocked: false
  },
  coal: {
    id: 'coal',
    name: 'Coal',
    icon: 'coal',
    description: 'A combustible black rock used as fuel.',
    tier: 2,
    unlocked: false
  },
  plant: {
    id: 'plant',
    name: 'Plant',
    icon: 'plant',
    description: 'A living organism that grows in soil.',
    tier: 2,
    unlocked: false
  },
  tree: {
    id: 'tree',
    name: 'Tree',
    icon: 'tree',
    description: 'A large plant with a woody trunk.',
    tier: 2,
    unlocked: false
  },
  flower: {
    id: 'flower',
    name: 'Flower',
    icon: 'flower',
    description: 'The reproductive structure of plants.',
    tier: 2,
    unlocked: false
  },
  grass: {
    id: 'grass',
    name: 'Grass',
    icon: 'grass',
    description: 'A common plant with narrow green leaves.',
    tier: 2,
    unlocked: false
  },
  wood: {
    id: 'wood',
    name: 'Wood',
    icon: 'wood',
    description: 'The hard fibrous material from trees.',
    tier: 2,
    unlocked: false
  },
  paper: {
    id: 'paper',
    name: 'Paper',
    icon: 'paper',
    description: 'Material made from wood pulp used for writing.',
    tier: 2,
    unlocked: false
  },
  wheat: {
    id: 'wheat',
    name: 'Wheat',
    icon: 'wheat',
    description: 'A cereal grain used to make flour.',
    tier: 2,
    unlocked: false
  },
  rice: {
    id: 'rice',
    name: 'Rice',
    icon: 'rice',
    description: 'A cereal grain that is a staple food worldwide.',
    tier: 2,
    unlocked: false
  },
  chicken: {
    id: 'chicken',
    name: 'Chicken',
    icon: 'chicken',
    description: 'A domesticated bird kept for eggs and meat.',
    tier: 2,
    unlocked: false
  },
  cow: {
    id: 'cow',
    name: 'Cow',
    icon: 'cow',
    description: 'A domesticated animal kept for milk and meat.',
    tier: 2,
    unlocked: false
  },
  tool: {
    id: 'tool',
    name: 'Tool',
    icon: 'tool',
    description: 'A device used to carry out a particular function.',
    tier: 2,
    unlocked: false
  },
  electricity: {
    id: 'electricity',
    name: 'Electricity',
    icon: 'electricity',
    description: 'A form of energy resulting from charged particles.',
    tier: 2,
    unlocked: false
  },
  wind: {
    id: 'wind',
    name: 'Wind',
    icon: 'wind',
    description: 'Air in natural motion, as that moving horizontally.',
    tier: 2,
    unlocked: false
  },
  cold: {
    id: 'cold',
    name: 'Cold',
    icon: 'cold',
    description: 'The absence of heat or warmth.',
    tier: 2,
    unlocked: false
  },
  sugar: {
    id: 'sugar',
    name: 'Sugar',
    icon: 'sugar',
    description: 'A sweet crystalline substance used in cooking.',
    tier: 2,
    unlocked: false
  },
  yeast: {
    id: 'yeast',
    name: 'Yeast',
    icon: 'yeast',
    description: 'A microscopic fungus used in baking and brewing.',
    tier: 2,
    unlocked: false
  },
  egg: {
    id: 'egg',
    name: 'Egg',
    icon: 'egg',
    description: 'A food product produced by birds.',
    tier: 2,
    unlocked: false
  },
  milk: {
    id: 'milk',
    name: 'Milk',
    icon: 'milk',
    description: 'A white liquid produced by mammals.',
    tier: 2,
    unlocked: false
  },
  meat: {
    id: 'meat',
    name: 'Meat',
    icon: 'meat',
    description: 'The flesh of an animal used as food.',
    tier: 2,
    unlocked: false
  },
  fish: {
    id: 'fish',
    name: 'Fish',
    icon: 'fish',
    description: 'An aquatic animal used as food.',
    tier: 2,
    unlocked: false
  },
  spice: {
    id: 'spice',
    name: 'Spice',
    icon: 'spice',
    description: 'A vegetable substance used to flavor food.',
    tier: 2,
    unlocked: false
  },
  herb: {
    id: 'herb',
    name: 'Herb',
    icon: 'herb',
    description: 'A plant with savory or aromatic properties.',
    tier: 2,
    unlocked: false
  },
  vegetable: {
    id: 'vegetable',
    name: 'Vegetable',
    icon: 'vegetable',
    description: 'An edible plant or part of a plant.',
    tier: 2,
    unlocked: false
  },
  fruit: {
    id: 'fruit',
    name: 'Fruit',
    icon: 'fruit',
    description: 'The sweet and fleshy part of a plant.',
    tier: 2,
    unlocked: false
  },
  ceramics: {
    id: 'ceramics',
    name: 'Ceramics',
    icon: 'pottery',
    description: 'Objects made from clay and hardened by heat.',
    tier: 2,
    unlocked: false
  },
  
  // TIER 3: Complex combinations (30 elements)
  flour: {
    id: 'flour',
    name: 'Flour',
    icon: 'flour',
    description: 'Ground wheat used for baking.',
    tier: 3,
    unlocked: false
  },
  butter: {
    id: 'butter',
    name: 'Butter',
    icon: 'butter',
    description: 'A dairy product made from milk or cream.',
    tier: 3,
    unlocked: false
  },
  cheese: {
    id: 'cheese',
    name: 'Cheese',
    icon: 'cheese',
    description: 'A food made from milk curds.',
    tier: 3,
    unlocked: false
  },
  cream: {
    id: 'cream',
    name: 'Cream',
    icon: 'cream',
    description: 'The fatty part of milk that rises to the top.',
    tier: 3,
    unlocked: false
  },
  dough: {
    id: 'dough',
    name: 'Dough',
    icon: 'dough',
    description: 'A mixture of flour and water used for baking.',
    tier: 3,
    unlocked: false
  },
  batter: {
    id: 'batter',
    name: 'Batter',
    icon: 'batter',
    description: 'A semi-liquid mixture of flour, eggs, and milk.',
    tier: 3,
    unlocked: false
  },
  broth: {
    id: 'broth',
    name: 'Broth',
    icon: 'broth',
    description: 'A savory liquid made by simmering meat or vegetables.',
    tier: 3,
    unlocked: false
  },
  sauce: {
    id: 'sauce',
    name: 'Sauce',
    icon: 'sauce',
    description: 'A liquid or semi-solid food served with other foods.',
    tier: 3,
    unlocked: false
  },
  chocolate: {
    id: 'chocolate',
    name: 'Chocolate',
    icon: 'chocolate',
    description: 'A food product made from cacao beans.',
    tier: 3,
    unlocked: false
  },
  honey: {
    id: 'honey',
    name: 'Honey',
    icon: 'honey',
    description: 'A sweet food made by bees using nectar from flowers.',
    tier: 3,
    unlocked: false
  },
  jam: {
    id: 'jam',
    name: 'Jam',
    icon: 'jam',
    description: 'A sweet spread made from fruit and sugar.',
    tier: 3,
    unlocked: false
  },
  vinegar: {
    id: 'vinegar',
    name: 'Vinegar',
    icon: 'vinegar',
    description: 'An acidic liquid used in cooking and pickling.',
    tier: 3,
    unlocked: false
  },
  noodle: {
    id: 'noodle',
    name: 'Noodle',
    icon: 'noodle',
    description: 'A strip of pasta made from dough.',
    tier: 3,
    unlocked: false
  },
  cookedRice: {
    id: 'cookedRice',
    name: 'Cooked Rice',
    icon: 'rice',
    description: 'Grains of rice that have been boiled or steamed.',
    tier: 3,
    unlocked: false
  },
  bean: {
    id: 'bean',
    name: 'Bean',
    icon: 'bean',
    description: 'The edible seed of various plants in the legume family.',
    tier: 3,
    unlocked: false
  },
  potato: {
    id: 'potato',
    name: 'Potato',
    icon: 'potato',
    description: 'A starchy root vegetable.',
    tier: 3,
    unlocked: false
  },
  mushroom: {
    id: 'mushroom',
    name: 'Mushroom',
    icon: 'mushroom',
    description: 'The fleshy, spore-bearing fruiting body of a fungus.',
    tier: 3,
    unlocked: false
  },
  tofu: {
    id: 'tofu',
    name: 'Tofu',
    icon: 'tofu',
    description: 'A food made from condensed soy milk.',
    tier: 3,
    unlocked: false
  },
  coffee: {
    id: 'coffee',
    name: 'Coffee',
    icon: 'coffee',
    description: 'A brewed drink prepared from roasted coffee beans.',
    tier: 3,
    unlocked: false
  },
  tea: {
    id: 'tea',
    name: 'Tea',
    icon: 'tea',
    description: 'A hot drink made by infusing leaves in water.',
    tier: 3,
    unlocked: false
  },
  wine: {
    id: 'wine',
    name: 'Wine',
    icon: 'wine',
    description: 'An alcoholic drink made from fermented grape juice.',
    tier: 3,
    unlocked: false
  },
  beer: {
    id: 'beer',
    name: 'Beer',
    icon: 'beer',
    description: 'An alcoholic drink made from fermented grain.',
    tier: 3,
    unlocked: false
  },
  knife: {
    id: 'knife',
    name: 'Knife',
    icon: 'knife',
    description: 'A cutting tool with a sharp blade.',
    tier: 3,
    unlocked: false
  },
  pot: {
    id: 'pot',
    name: 'Pot',
    icon: 'pot',
    description: 'A cooking vessel for making soups and stews.',
    tier: 3,
    unlocked: false
  },
  pan: {
    id: 'pan',
    name: 'Pan',
    icon: 'pan',
    description: 'A flat bottomed cooking container.',
    tier: 3,
    unlocked: false
  },
  oven: {
    id: 'oven',
    name: 'Oven',
    icon: 'oven',
    description: 'An enclosed chamber for cooking food.',
    tier: 3,
    unlocked: false
  },
  grill: {
    id: 'grill',
    name: 'Grill',
    icon: 'grill',
    description: 'A cooking device with a heat source beneath a grate.',
    tier: 3,
    unlocked: false
  },
  frozenDessert: {
    id: 'frozenDessert',
    name: 'Frozen Dessert',
    icon: 'frozenDessert',
    description: 'A sweet dish made with ice or frozen ingredients.',
    tier: 3,
    unlocked: false
  },
  marinade: {
    id: 'marinade',
    name: 'Marinade',
    icon: 'marinade',
    description: 'A sauce in which meat, fish, or other food is soaked before cooking.',
    tier: 3,
    unlocked: false
  },
  
  // TIER 4: Advanced combinations (15 elements)
  bread: {
    id: 'bread',
    name: 'Bread',
    icon: 'bread',
    description: 'A staple food made from dough of flour and water.',
    tier: 4,
    unlocked: false
  },
  pastry: {
    id: 'pastry',
    name: 'Pastry',
    icon: 'pastry',
    description: 'A dough of flour, fat, and water, baked and often filled.',
    tier: 4,
    unlocked: false
  },
  soup: {
    id: 'soup',
    name: 'Soup',
    icon: 'soup',
    description: 'A liquid dish typically made by boiling ingredients.',
    tier: 4,
    unlocked: false
  },
  stew: {
    id: 'stew',
    name: 'Stew',
    icon: 'stew',
    description: 'A slowly cooked dish of meat and vegetables in liquid.',
    tier: 4,
    unlocked: false
  },
  salad: {
    id: 'salad',
    name: 'Salad',
    icon: 'salad',
    description: 'A cold dish of various vegetables with dressing.',
    tier: 4,
    unlocked: false
  },
  sandwich: {
    id: 'sandwich',
    name: 'Sandwich',
    icon: 'sandwich',
    description: 'Two pieces of bread with a filling between them.',
    tier: 4,
    unlocked: false
  },
  roast: {
    id: 'roast',
    name: 'Roast',
    icon: 'roast',
    description: 'Meat cooked by dry heat in an oven or over fire.',
    tier: 4,
    unlocked: false
  },
  pasta: {
    id: 'pasta',
    name: 'Pasta Dish',
    icon: 'pasta',
    description: 'A dish with pasta as the primary ingredient.',
    tier: 4,
    unlocked: false
  },
  riceDish: {
    id: 'riceDish',
    name: 'Rice Dish',
    icon: 'riceDish',
    description: 'A dish with rice as the primary ingredient.',
    tier: 4,
    unlocked: false
  },
  curry: {
    id: 'curry',
    name: 'Curry',
    icon: 'curry',
    description: 'A spiced dish cooked in an Indian style.',
    tier: 4,
    unlocked: false
  },
  stirFry: {
    id: 'stirFry',
    name: 'Stir Fry',
    icon: 'stirFry',
    description: 'A dish of small pieces of meat and vegetables fried quickly.',
    tier: 4,
    unlocked: false
  },
  iceCream: {
    id: 'iceCream',
    name: 'Ice Cream',
    icon: 'iceCream',
    description: 'A frozen dessert made from cream or milk and sugar.',
    tier: 4,
    unlocked: false
  },
  pie: {
    id: 'pie',
    name: 'Pie',
    icon: 'pie',
    description: 'A baked dish with a filling enclosed in pastry.',
    tier: 4,
    unlocked: false
  },
  cookie: {
    id: 'cookie',
    name: 'Cookie',
    icon: 'cookie',
    description: 'A small, flat, sweet baked food.',
    tier: 4,
    unlocked: false
  },
  pizza: {
    id: 'pizza',
    name: 'Pizza',
    icon: 'pizza',
    description: 'A dish of Italian origin with a flat base topped with ingredients.',
    tier: 4,
    unlocked: false
  },
  bbq: {
    id: 'bbq',
    name: 'BBQ',
    icon: 'bbq',
    description: 'Food cooked by the barbecue method.',
    tier: 4,
    unlocked: false
  },
  
  // TIER 5: Final creations (5 elements)
  cake: {
    id: 'cake',
    name: 'Wedding Cake',
    icon: 'cake',
    description: 'A multi-tiered sweet cake used for wedding celebrations.',
    tier: 5,
    unlocked: false
  },
  feastPlatter: {
    id: 'feastPlatter',
    name: 'Feast Platter',
    icon: 'feastPlatter',
    description: 'An elaborate arrangement of multiple dishes for celebration.',
    tier: 5,
    unlocked: false
  },
  gourmetMeal: {
    id: 'gourmetMeal',
    name: 'Gourmet Meal',
    icon: 'gourmetMeal',
    description: 'A sophisticated dish prepared with high-quality ingredients and expert technique.',
    tier: 5,
    unlocked: false
  },
  holiday: {
    id: 'holiday',
    name: 'Holiday Dinner',
    icon: 'holiday',
    description: 'A traditional meal served during special occasions and holidays.',
    tier: 5,
    unlocked: false
  },
  masterChefSpecial: {
    id: 'masterChefSpecial',
    name: 'Master Chef Special',
    icon: 'masterChefSpecial',
    description: 'The pinnacle of culinary achievement, a perfect harmony of flavors and techniques.',
    tier: 5,
    unlocked: false
  }
});
