export interface Element {
  id: string;
  name: string;
  icon: string;
  description?: string;
  isBasic?: boolean;
  unlocked: boolean;
}

export interface ElementsState {
  [id: string]: Element;
}

// Define all game elements with their properties
export const createInitialElements = (): ElementsState => ({
  // Basic elements (starting elements)
  air: {
    id: 'air',
    name: 'Air',
    icon: 'air',
    description: 'One of the four basic elements.',
    isBasic: true,
    unlocked: true
  },
  earth: {
    id: 'earth',
    name: 'Earth',
    icon: 'earth',
    description: 'One of the four basic elements.',
    isBasic: true,
    unlocked: true
  },
  fire: {
    id: 'fire',
    name: 'Fire',
    icon: 'fire',
    description: 'One of the four basic elements.',
    isBasic: true,
    unlocked: true
  },
  water: {
    id: 'water',
    name: 'Water',
    icon: 'water',
    description: 'One of the four basic elements.',
    isBasic: true,
    unlocked: true
  },
  
  // Tier 1 combinations
  steam: {
    id: 'steam',
    name: 'Steam',
    icon: 'steam',
    description: 'Water that has been heated to its boiling point.',
    unlocked: false
  },
  mud: {
    id: 'mud',
    name: 'Mud',
    icon: 'mud',
    description: 'A mixture of earth and water.',
    unlocked: false
  },
  dust: {
    id: 'dust',
    name: 'Dust',
    icon: 'dust',
    description: 'Small particles of earth suspended in air.',
    unlocked: false
  },
  energy: {
    id: 'energy',
    name: 'Energy',
    icon: 'energy',
    description: 'The power generated by fire and air together.',
    unlocked: false
  },
  lava: {
    id: 'lava',
    name: 'Lava',
    icon: 'lava',
    description: 'Molten rock created when fire meets earth.',
    unlocked: false
  },
  
  // Tier 2 combinations
  stone: {
    id: 'stone',
    name: 'Stone',
    icon: 'stone',
    description: 'A hard piece of mineral matter.',
    unlocked: false
  },
  metal: {
    id: 'metal',
    name: 'Metal',
    icon: 'metal',
    description: 'A material that conducts heat and electricity.',
    unlocked: false
  },
  clay: {
    id: 'clay',
    name: 'Clay',
    icon: 'clay',
    description: 'Fine-grained earth that can be molded when wet.',
    unlocked: false
  },
  glass: {
    id: 'glass',
    name: 'Glass',
    icon: 'glass',
    description: 'A transparent substance made from sand.',
    unlocked: false
  },
  salt: {
    id: 'salt',
    name: 'Salt',
    icon: 'salt',
    description: 'A crystalline mineral used for seasoning.',
    unlocked: false
  },
  
  // Cooking tools
  pot: {
    id: 'pot',
    name: 'Pot',
    icon: 'pot',
    description: 'A cooking vessel for making soups and stews.',
    unlocked: false
  },
  pan: {
    id: 'pan',
    name: 'Pan',
    icon: 'pan',
    description: 'A flat bottomed cooking container.',
    unlocked: false
  },
  oven: {
    id: 'oven',
    name: 'Oven',
    icon: 'oven',
    description: 'An enclosed chamber for cooking food.',
    unlocked: false
  },
  knife: {
    id: 'knife',
    name: 'Knife',
    icon: 'knife',
    description: 'A cutting tool with a sharp blade.',
    unlocked: false
  },
  
  // Ingredients
  dough: {
    id: 'dough',
    name: 'Dough',
    icon: 'dough',
    description: 'A mixture of flour and water used for baking.',
    unlocked: false
  },
  flour: {
    id: 'flour',
    name: 'Flour',
    icon: 'flour',
    description: 'Ground grain used for baking.',
    unlocked: false
  },
  sugar: {
    id: 'sugar',
    name: 'Sugar',
    icon: 'sugar',
    description: 'A sweet crystalline substance used in cooking.',
    unlocked: false
  },
  egg: {
    id: 'egg',
    name: 'Egg',
    icon: 'egg',
    description: 'A food product produced by birds, reptiles, and fish.',
    unlocked: false
  },
  milk: {
    id: 'milk',
    name: 'Milk',
    icon: 'milk',
    description: 'A white liquid produced by mammals.',
    unlocked: false
  },
  butter: {
    id: 'butter',
    name: 'Butter',
    icon: 'butter',
    description: 'A dairy product made from milk or cream.',
    unlocked: false
  },
  cheese: {
    id: 'cheese',
    name: 'Cheese',
    icon: 'cheese',
    description: 'A food made from milk curds.',
    unlocked: false
  },
  meat: {
    id: 'meat',
    name: 'Meat',
    icon: 'meat',
    description: 'The flesh of an animal used as food.',
    unlocked: false
  },
  fish: {
    id: 'fish',
    name: 'Fish',
    icon: 'fish',
    description: 'An aquatic animal used as food.',
    unlocked: false
  },
  vegetable: {
    id: 'vegetable',
    name: 'Vegetable',
    icon: 'vegetable',
    description: 'An edible plant or part of a plant.',
    unlocked: false
  },
  fruit: {
    id: 'fruit',
    name: 'Fruit',
    icon: 'fruit',
    description: 'The sweet and fleshy part of a plant.',
    unlocked: false
  },
  spice: {
    id: 'spice',
    name: 'Spice',
    icon: 'spice',
    description: 'A vegetable substance used to flavor food.',
    unlocked: false
  },
  
  // Final foods
  bread: {
    id: 'bread',
    name: 'Bread',
    icon: 'bread',
    description: 'A staple food made from dough of flour and water.',
    unlocked: false
  },
  cake: {
    id: 'cake',
    name: 'Cake',
    icon: 'cake',
    description: 'A sweet baked food made from flour, sugar, and other ingredients.',
    unlocked: false
  },
  pie: {
    id: 'pie',
    name: 'Pie',
    icon: 'pie',
    description: 'A baked dish with a filling enclosed in pastry.',
    unlocked: false
  },
  soup: {
    id: 'soup',
    name: 'Soup',
    icon: 'soup',
    description: 'A liquid dish typically made by boiling ingredients.',
    unlocked: false
  },
  stew: {
    id: 'stew',
    name: 'Stew',
    icon: 'stew',
    description: 'A slowly cooked dish of meat and vegetables in liquid.',
    unlocked: false
  },
  pizza: {
    id: 'pizza',
    name: 'Pizza',
    icon: 'pizza',
    description: 'A dish of Italian origin with a flat base topped with ingredients.',
    unlocked: false
  },
  pasta: {
    id: 'pasta',
    name: 'Pasta',
    icon: 'pasta',
    description: 'A dish made from flour and water, formed into various shapes.',
    unlocked: false
  },
  salad: {
    id: 'salad',
    name: 'Salad',
    icon: 'salad',
    description: 'A cold dish of various vegetables with dressing.',
    unlocked: false
  },
  iceCream: {
    id: 'iceCream',
    name: 'Ice Cream',
    icon: 'iceCream',
    description: 'A frozen dessert made from cream or milk and sugar.',
    unlocked: false
  },
  chocolate: {
    id: 'chocolate',
    name: 'Chocolate',
    icon: 'chocolate',
    description: 'A food product made from cocoa beans.',
    unlocked: false
  },
  coffee: {
    id: 'coffee',
    name: 'Coffee',
    icon: 'coffee',
    description: 'A brewed drink prepared from roasted coffee beans.',
    unlocked: false
  },
  tea: {
    id: 'tea',
    name: 'Tea',
    icon: 'tea',
    description: 'A hot drink made by infusing leaves in water.',
    unlocked: false
  },
  wine: {
    id: 'wine',
    name: 'Wine',
    icon: 'wine',
    description: 'An alcoholic drink made from fermented grape juice.',
    unlocked: false
  },
  beer: {
    id: 'beer',
    name: 'Beer',
    icon: 'beer',
    description: 'An alcoholic drink made from fermented grain.',
    unlocked: false
  }
});
